linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
  disable:
    - golint  # deprecated, replaced by revive

run:
  timeout: 5m
  skip-dirs:
    - tests

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0
