server:
  port: "50052"
  environment: "development"
  serviceName: "user-service"
  logLevel: "debug"
  gracefulShutdownTimeout: "30s"

database:
  host: "localhost"
  port: "5432"
  name: "nexcart_user"
  user: "postgres"
  sslMode: "disable"
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: "15m"
  connMaxIdleTime: "15m"

redis:
  host: "localhost"  # Changed from "redis" to "localhost"
  port: "6379"

auth:
  secretKey: "your_jwt_secret_key_here"
  accessTokenDuration: "24h"
  refreshTokenDuration: "168h"  # 7 days

rateLimiter:
  attempts: 5
  duration: "1m"



