// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base messages
type VariantAttributeValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // e.g., 'Color'
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // e.g., 'Red'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantAttributeValue) Reset() {
	*x = VariantAttributeValue{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantAttributeValue) ProtoMessage() {}

func (x *VariantAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantAttributeValue.ProtoReflect.Descriptor instead.
func (*VariantAttributeValue) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *VariantAttributeValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariantAttributeValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VariantImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,4,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantImage) Reset() {
	*x = VariantImage{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantImage) ProtoMessage() {}

func (x *VariantImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantImage.ProtoReflect.Descriptor instead.
func (*VariantImage) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *VariantImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VariantImage) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *VariantImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VariantImage) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *VariantImage) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *VariantImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VariantImage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductVariant struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice *wrapperspb.DoubleValue  `protobuf:"bytes,6,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	Attributes    []*VariantAttributeValue `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Images        []*VariantImage          `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Inherited fields from parent product
	Description      string                  `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                  `protobuf:"bytes,13,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Specifications   []*ProductSpecification `protobuf:"bytes,14,rep,name=specifications,proto3" json:"specifications,omitempty"`
	Tags             []*ProductTag           `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories       []*Category             `protobuf:"bytes,16,rep,name=categories,proto3" json:"categories,omitempty"`
	Brand            *Brand                  `protobuf:"bytes,17,opt,name=brand,proto3" json:"brand,omitempty"`
	Seo              *ProductSEO             `protobuf:"bytes,18,opt,name=seo,proto3" json:"seo,omitempty"`
	Shipping         *ProductShipping        `protobuf:"bytes,19,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Discount         *ProductDiscount        `protobuf:"bytes,20,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductVariant) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductVariant) GetDiscountPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DiscountPrice
	}
	return nil
}

func (x *ProductVariant) GetAttributes() []*VariantAttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProductVariant) GetImages() []*VariantImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductVariant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductVariant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProductVariant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductVariant) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *ProductVariant) GetSpecifications() []*ProductSpecification {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *ProductVariant) GetTags() []*ProductTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductVariant) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ProductVariant) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *ProductVariant) GetSeo() *ProductSEO {
	if x != nil {
		return x.Seo
	}
	return nil
}

func (x *ProductVariant) GetShipping() *ProductShipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *ProductVariant) GetDiscount() *ProductDiscount {
	if x != nil {
		return x.Discount
	}
	return nil
}

type ProductTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductTag) Reset() {
	*x = ProductTag{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTag) ProtoMessage() {}

func (x *ProductTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTag.ProtoReflect.Descriptor instead.
func (*ProductTag) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductTag) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductTag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ProductTag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductTag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductAttribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductAttribute) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProductAttribute) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductAttribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSpecification) Reset() {
	*x = ProductSpecification{}
	mi := &file_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSpecification) ProtoMessage() {}

func (x *ProductSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSpecification.ProtoReflect.Descriptor instead.
func (*ProductSpecification) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductSpecification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductSpecification) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductSpecification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSpecification) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProductSpecification) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductSpecification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductSpecification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductSEO struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId       string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MetaTitle       string                 `protobuf:"bytes,3,opt,name=meta_title,json=metaTitle,proto3" json:"meta_title,omitempty"`
	MetaDescription string                 `protobuf:"bytes,4,opt,name=meta_description,json=metaDescription,proto3" json:"meta_description,omitempty"`
	Keywords        []string               `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductSEO) Reset() {
	*x = ProductSEO{}
	mi := &file_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSEO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSEO) ProtoMessage() {}

func (x *ProductSEO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSEO.ProtoReflect.Descriptor instead.
func (*ProductSEO) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductSEO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductSEO) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductSEO) GetMetaTitle() string {
	if x != nil {
		return x.MetaTitle
	}
	return ""
}

func (x *ProductSEO) GetMetaDescription() string {
	if x != nil {
		return x.MetaDescription
	}
	return ""
}

func (x *ProductSEO) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ProductSEO) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductSEO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductSEO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductShipping struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId        string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FreeShipping     bool                   `protobuf:"varint,3,opt,name=free_shipping,json=freeShipping,proto3" json:"free_shipping,omitempty"`
	EstimatedDays    int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	ExpressAvailable bool                   `protobuf:"varint,5,opt,name=express_available,json=expressAvailable,proto3" json:"express_available,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductShipping) Reset() {
	*x = ProductShipping{}
	mi := &file_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductShipping) ProtoMessage() {}

func (x *ProductShipping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductShipping.ProtoReflect.Descriptor instead.
func (*ProductShipping) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductShipping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductShipping) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductShipping) GetFreeShipping() bool {
	if x != nil {
		return x.FreeShipping
	}
	return false
}

func (x *ProductShipping) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

func (x *ProductShipping) GetExpressAvailable() bool {
	if x != nil {
		return x.ExpressAvailable
	}
	return false
}

func (x *ProductShipping) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductShipping) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDiscount) Reset() {
	*x = ProductDiscount{}
	mi := &file_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDiscount) ProtoMessage() {}

func (x *ProductDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDiscount.ProtoReflect.Descriptor instead.
func (*ProductDiscount) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *ProductDiscount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductDiscount) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductDiscount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductDiscount) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ProductDiscount) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ProductDiscount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductDiscount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Product struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug             string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description      string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                  `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Price            float64                 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`                                    // Populated from default variant
	DiscountPrice    *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"` // Populated from default variant
	Sku              string                  `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`                                          // Populated from default variant
	Weight           *wrapperspb.DoubleValue `protobuf:"bytes,11,opt,name=weight,proto3" json:"weight,omitempty"`
	IsPublished      bool                    `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp  `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BrandId          *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Brand            *Brand                  `protobuf:"bytes,16,opt,name=brand,proto3" json:"brand,omitempty"`
	Images           []*ProductImage         `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
	Categories       []*Category             `protobuf:"bytes,18,rep,name=categories,proto3" json:"categories,omitempty"`
	Variants         []*ProductVariant       `protobuf:"bytes,19,rep,name=variants,proto3" json:"variants,omitempty"`
	DefaultVariantId *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=default_variant_id,json=defaultVariantId,proto3" json:"default_variant_id,omitempty"`
	// New fields
	Tags           []*ProductTag           `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes     []*ProductAttribute     `protobuf:"bytes,22,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Specifications []*ProductSpecification `protobuf:"bytes,23,rep,name=specifications,proto3" json:"specifications,omitempty"`
	Seo            *ProductSEO             `protobuf:"bytes,24,opt,name=seo,proto3" json:"seo,omitempty"`
	Shipping       *ProductShipping        `protobuf:"bytes,25,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Discount       *ProductDiscount        `protobuf:"bytes,26,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDiscountPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DiscountPrice
	}
	return nil
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetWeight() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Product) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetBrandId() *wrapperspb.StringValue {
	if x != nil {
		return x.BrandId
	}
	return nil
}

func (x *Product) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *Product) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Product) GetDefaultVariantId() *wrapperspb.StringValue {
	if x != nil {
		return x.DefaultVariantId
	}
	return nil
}

func (x *Product) GetTags() []*ProductTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetSpecifications() []*ProductSpecification {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *Product) GetSeo() *ProductSEO {
	if x != nil {
		return x.Seo
	}
	return nil
}

func (x *Product) GetShipping() *ProductShipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *Product) GetDiscount() *ProductDiscount {
	if x != nil {
		return x.Discount
	}
	return nil
}

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,4,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *ProductImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductImage) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *ProductImage) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProductImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductImage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Brand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Added for soft delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_proto_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{11}
}

func (x *Brand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Brand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Brand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Brand) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Brand) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ParentName    string                  `protobuf:"bytes,6,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Added for soft delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{12}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetParentId() *wrapperspb.StringValue {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *Category) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Category) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Product related messages
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetProductRequest_Id
	//	*GetProductRequest_Slug
	Identifier    isGetProductRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{14}
}

func (x *GetProductRequest) GetIdentifier() isGetProductRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetProductRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetProductRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetProductRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetProductRequest_Identifier interface {
	isGetProductRequest_Identifier()
}

type GetProductRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetProductRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetProductRequest_Id) isGetProductRequest_Identifier() {}

func (*GetProductRequest_Slug) isGetProductRequest_Identifier() {}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_proto_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{18}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{19}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Brand related messages
type GetBrandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetBrandRequest_Id
	//	*GetBrandRequest_Slug
	Identifier    isGetBrandRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandRequest) Reset() {
	*x = GetBrandRequest{}
	mi := &file_proto_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandRequest) ProtoMessage() {}

func (x *GetBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandRequest.ProtoReflect.Descriptor instead.
func (*GetBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{20}
}

func (x *GetBrandRequest) GetIdentifier() isGetBrandRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetBrandRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetBrandRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetBrandRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetBrandRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetBrandRequest_Identifier interface {
	isGetBrandRequest_Identifier()
}

type GetBrandRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetBrandRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetBrandRequest_Id) isGetBrandRequest_Identifier() {}

func (*GetBrandRequest_Slug) isGetBrandRequest_Identifier() {}

type ListBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsRequest) Reset() {
	*x = ListBrandsRequest{}
	mi := &file_proto_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsRequest) ProtoMessage() {}

func (x *ListBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsRequest.ProtoReflect.Descriptor instead.
func (*ListBrandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{21}
}

func (x *ListBrandsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBrandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*Brand               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsResponse) Reset() {
	*x = ListBrandsResponse{}
	mi := &file_proto_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsResponse) ProtoMessage() {}

func (x *ListBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsResponse.ProtoReflect.Descriptor instead.
func (*ListBrandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{22}
}

func (x *ListBrandsResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ListBrandsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandRequest) Reset() {
	*x = CreateBrandRequest{}
	mi := &file_proto_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandRequest) ProtoMessage() {}

func (x *CreateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandRequest.ProtoReflect.Descriptor instead.
func (*CreateBrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBrandRequest) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

// Category related messages
type GetCategoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetCategoryRequest_Id
	//	*GetCategoryRequest_Slug
	Identifier    isGetCategoryRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_proto_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{24}
}

func (x *GetCategoryRequest) GetIdentifier() isGetCategoryRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCategoryRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetCategoryRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCategoryRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetCategoryRequest_Identifier interface {
	isGetCategoryRequest_Identifier()
}

type GetCategoryRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetCategoryRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetCategoryRequest_Id) isGetCategoryRequest_Identifier() {}

func (*GetCategoryRequest_Slug) isGetCategoryRequest_Identifier() {}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_proto_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{25}
}

func (x *ListCategoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_proto_product_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{26}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_proto_product_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{27}
}

func (x *CreateCategoryRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// Image upload related messages
type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_proto_product_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{28}
}

func (x *UploadImageRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadImageRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *UploadImageRequest) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *UploadImageRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_proto_product_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{29}
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadImageResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UploadImageResponse) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *UploadImageResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_proto_product_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteImageRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type DeleteImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageResponse) Reset() {
	*x = DeleteImageResponse{}
	mi := &file_proto_product_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageResponse) ProtoMessage() {}

func (x *DeleteImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageResponse.ProtoReflect.Descriptor instead.
func (*DeleteImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SKU generation related messages
type GenerateSKUPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandName     string                 `protobuf:"bytes,1,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSKUPreviewRequest) Reset() {
	*x = GenerateSKUPreviewRequest{}
	mi := &file_proto_product_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSKUPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSKUPreviewRequest) ProtoMessage() {}

func (x *GenerateSKUPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSKUPreviewRequest.ProtoReflect.Descriptor instead.
func (*GenerateSKUPreviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{32}
}

func (x *GenerateSKUPreviewRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GenerateSKUPreviewRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GenerateSKUPreviewRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GenerateSKUPreviewRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type GenerateSKUPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSKUPreviewResponse) Reset() {
	*x = GenerateSKUPreviewResponse{}
	mi := &file_proto_product_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSKUPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSKUPreviewResponse) ProtoMessage() {}

func (x *GenerateSKUPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSKUPreviewResponse.ProtoReflect.Descriptor instead.
func (*GenerateSKUPreviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{33}
}

func (x *GenerateSKUPreviewResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"A\n" +
	"\x15VariantAttributeValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xfc\x01\n" +
	"\fVariantImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x04 \x01(\tR\aaltText\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd2\x06\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12C\n" +
	"\x0ediscount_price\x18\x06 \x01(\v2\x1c.google.protobuf.DoubleValueR\rdiscountPrice\x12>\n" +
	"\n" +
	"attributes\x18\b \x03(\v2\x1e.product.VariantAttributeValueR\n" +
	"attributes\x12-\n" +
	"\x06images\x18\t \x03(\v2\x15.product.VariantImageR\x06images\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\r \x01(\tR\x10shortDescription\x12E\n" +
	"\x0especifications\x18\x0e \x03(\v2\x1d.product.ProductSpecificationR\x0especifications\x12'\n" +
	"\x04tags\x18\x0f \x03(\v2\x13.product.ProductTagR\x04tags\x121\n" +
	"\n" +
	"categories\x18\x10 \x03(\v2\x11.product.CategoryR\n" +
	"categories\x12$\n" +
	"\x05brand\x18\x11 \x01(\v2\x0e.product.BrandR\x05brand\x12%\n" +
	"\x03seo\x18\x12 \x01(\v2\x13.product.ProductSEOR\x03seo\x124\n" +
	"\bshipping\x18\x13 \x01(\v2\x18.product.ProductShippingR\bshipping\x124\n" +
	"\bdiscount\x18\x14 \x01(\v2\x18.product.ProductDiscountR\bdiscount\"\xc3\x01\n" +
	"\n" +
	"ProductTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x01\n" +
	"\x10ProductAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf9\x01\n" +
	"\x14ProductSpecification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xab\x02\n" +
	"\n" +
	"ProductSEO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"meta_title\x18\x03 \x01(\tR\tmetaTitle\x12)\n" +
	"\x10meta_description\x18\x04 \x01(\tR\x0fmetaDescription\x12\x1a\n" +
	"\bkeywords\x18\x05 \x03(\tR\bkeywords\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x02\n" +
	"\x0fProductShipping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12#\n" +
	"\rfree_shipping\x18\x03 \x01(\bR\ffreeShipping\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\x12+\n" +
	"\x11express_available\x18\x05 \x01(\bR\x10expressAvailable\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x02\n" +
	"\x0fProductDiscount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xce\b\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x05 \x01(\tR\x10shortDescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12C\n" +
	"\x0ediscount_price\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\rdiscountPrice\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x124\n" +
	"\x06weight\x18\v \x01(\v2\x1c.google.protobuf.DoubleValueR\x06weight\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\bbrand_id\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\abrandId\x12$\n" +
	"\x05brand\x18\x10 \x01(\v2\x0e.product.BrandR\x05brand\x12-\n" +
	"\x06images\x18\x11 \x03(\v2\x15.product.ProductImageR\x06images\x121\n" +
	"\n" +
	"categories\x18\x12 \x03(\v2\x11.product.CategoryR\n" +
	"categories\x123\n" +
	"\bvariants\x18\x13 \x03(\v2\x17.product.ProductVariantR\bvariants\x12J\n" +
	"\x12default_variant_id\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\x10defaultVariantId\x12'\n" +
	"\x04tags\x18\x15 \x03(\v2\x13.product.ProductTagR\x04tags\x129\n" +
	"\n" +
	"attributes\x18\x16 \x03(\v2\x19.product.ProductAttributeR\n" +
	"attributes\x12E\n" +
	"\x0especifications\x18\x17 \x03(\v2\x1d.product.ProductSpecificationR\x0especifications\x12%\n" +
	"\x03seo\x18\x18 \x01(\v2\x13.product.ProductSEOR\x03seo\x124\n" +
	"\bshipping\x18\x19 \x01(\v2\x18.product.ProductShippingR\bshipping\x124\n" +
	"\bdiscount\x18\x1a \x01(\v2\x18.product.ProductDiscountR\bdiscount\"\xfc\x01\n" +
	"\fProductImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x04 \x01(\tR\aaltText\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x02\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xf1\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\tparent_id\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\bparentId\x12\x1f\n" +
	"\vparent_name\x18\x06 \x01(\tR\n" +
	"parentName\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"B\n" +
	"\x14CreateProductRequest\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"I\n" +
	"\x11GetProductRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"B\n" +
	"\x14UpdateProductRequest\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Z\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"G\n" +
	"\x0fGetBrandRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"=\n" +
	"\x11ListBrandsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x12ListBrandsResponse\x12&\n" +
	"\x06brands\x18\x01 \x03(\v2\x0e.product.BrandR\x06brands\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\":\n" +
	"\x12CreateBrandRequest\x12$\n" +
	"\x05brand\x18\x01 \x01(\v2\x0e.product.BrandR\x05brand\"J\n" +
	"\x12GetCategoryRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"A\n" +
	"\x15ListCategoriesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"a\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.product.CategoryR\n" +
	"categories\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x15CreateCategoryRequest\x12-\n" +
	"\bcategory\x18\x01 \x01(\v2\x11.product.CategoryR\bcategory\"\xb0\x01\n" +
	"\x12UploadImageRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\"{\n" +
	"\x13UploadImageResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"1\n" +
	"\x12DeleteImageRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"/\n" +
	"\x13DeleteImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x19GenerateSKUPreviewRequest\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x01 \x01(\tR\tbrandName\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\".\n" +
	"\x1aGenerateSKUPreviewResponse\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku2\xf0\a\n" +
	"\x0eProductService\x12@\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x10.product.Product\x12:\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x10.product.Product\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12@\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x10.product.Product\x12N\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12:\n" +
	"\vCreateBrand\x12\x1b.product.CreateBrandRequest\x1a\x0e.product.Brand\x124\n" +
	"\bGetBrand\x12\x18.product.GetBrandRequest\x1a\x0e.product.Brand\x12E\n" +
	"\n" +
	"ListBrands\x12\x1a.product.ListBrandsRequest\x1a\x1b.product.ListBrandsResponse\x12C\n" +
	"\x0eCreateCategory\x12\x1e.product.CreateCategoryRequest\x1a\x11.product.Category\x12=\n" +
	"\vGetCategory\x12\x1b.product.GetCategoryRequest\x1a\x11.product.Category\x12Q\n" +
	"\x0eListCategories\x12\x1e.product.ListCategoriesRequest\x1a\x1f.product.ListCategoriesResponse\x12H\n" +
	"\vUploadImage\x12\x1b.product.UploadImageRequest\x1a\x1c.product.UploadImageResponse\x12H\n" +
	"\vDeleteImage\x12\x1b.product.DeleteImageRequest\x1a\x1c.product.DeleteImageResponse\x12]\n" +
	"\x12GenerateSKUPreview\x12\".product.GenerateSKUPreviewRequest\x1a#.product.GenerateSKUPreviewResponseBEZCgithub.com/louai60/e-commerce_project/backend/product-service/protob\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_product_proto_goTypes = []any{
	(*VariantAttributeValue)(nil),      // 0: product.VariantAttributeValue
	(*VariantImage)(nil),               // 1: product.VariantImage
	(*ProductVariant)(nil),             // 2: product.ProductVariant
	(*ProductTag)(nil),                 // 3: product.ProductTag
	(*ProductAttribute)(nil),           // 4: product.ProductAttribute
	(*ProductSpecification)(nil),       // 5: product.ProductSpecification
	(*ProductSEO)(nil),                 // 6: product.ProductSEO
	(*ProductShipping)(nil),            // 7: product.ProductShipping
	(*ProductDiscount)(nil),            // 8: product.ProductDiscount
	(*Product)(nil),                    // 9: product.Product
	(*ProductImage)(nil),               // 10: product.ProductImage
	(*Brand)(nil),                      // 11: product.Brand
	(*Category)(nil),                   // 12: product.Category
	(*CreateProductRequest)(nil),       // 13: product.CreateProductRequest
	(*GetProductRequest)(nil),          // 14: product.GetProductRequest
	(*UpdateProductRequest)(nil),       // 15: product.UpdateProductRequest
	(*DeleteProductRequest)(nil),       // 16: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),      // 17: product.DeleteProductResponse
	(*ListProductsRequest)(nil),        // 18: product.ListProductsRequest
	(*ListProductsResponse)(nil),       // 19: product.ListProductsResponse
	(*GetBrandRequest)(nil),            // 20: product.GetBrandRequest
	(*ListBrandsRequest)(nil),          // 21: product.ListBrandsRequest
	(*ListBrandsResponse)(nil),         // 22: product.ListBrandsResponse
	(*CreateBrandRequest)(nil),         // 23: product.CreateBrandRequest
	(*GetCategoryRequest)(nil),         // 24: product.GetCategoryRequest
	(*ListCategoriesRequest)(nil),      // 25: product.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),     // 26: product.ListCategoriesResponse
	(*CreateCategoryRequest)(nil),      // 27: product.CreateCategoryRequest
	(*UploadImageRequest)(nil),         // 28: product.UploadImageRequest
	(*UploadImageResponse)(nil),        // 29: product.UploadImageResponse
	(*DeleteImageRequest)(nil),         // 30: product.DeleteImageRequest
	(*DeleteImageResponse)(nil),        // 31: product.DeleteImageResponse
	(*GenerateSKUPreviewRequest)(nil),  // 32: product.GenerateSKUPreviewRequest
	(*GenerateSKUPreviewResponse)(nil), // 33: product.GenerateSKUPreviewResponse
	(*timestamppb.Timestamp)(nil),      // 34: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil),     // 35: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil),     // 36: google.protobuf.StringValue
}
var file_proto_product_proto_depIdxs = []int32{
	34, // 0: product.VariantImage.created_at:type_name -> google.protobuf.Timestamp
	34, // 1: product.VariantImage.updated_at:type_name -> google.protobuf.Timestamp
	35, // 2: product.ProductVariant.discount_price:type_name -> google.protobuf.DoubleValue
	0,  // 3: product.ProductVariant.attributes:type_name -> product.VariantAttributeValue
	1,  // 4: product.ProductVariant.images:type_name -> product.VariantImage
	34, // 5: product.ProductVariant.created_at:type_name -> google.protobuf.Timestamp
	34, // 6: product.ProductVariant.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: product.ProductVariant.specifications:type_name -> product.ProductSpecification
	3,  // 8: product.ProductVariant.tags:type_name -> product.ProductTag
	12, // 9: product.ProductVariant.categories:type_name -> product.Category
	11, // 10: product.ProductVariant.brand:type_name -> product.Brand
	6,  // 11: product.ProductVariant.seo:type_name -> product.ProductSEO
	7,  // 12: product.ProductVariant.shipping:type_name -> product.ProductShipping
	8,  // 13: product.ProductVariant.discount:type_name -> product.ProductDiscount
	34, // 14: product.ProductTag.created_at:type_name -> google.protobuf.Timestamp
	34, // 15: product.ProductTag.updated_at:type_name -> google.protobuf.Timestamp
	34, // 16: product.ProductAttribute.created_at:type_name -> google.protobuf.Timestamp
	34, // 17: product.ProductAttribute.updated_at:type_name -> google.protobuf.Timestamp
	34, // 18: product.ProductSpecification.created_at:type_name -> google.protobuf.Timestamp
	34, // 19: product.ProductSpecification.updated_at:type_name -> google.protobuf.Timestamp
	34, // 20: product.ProductSEO.created_at:type_name -> google.protobuf.Timestamp
	34, // 21: product.ProductSEO.updated_at:type_name -> google.protobuf.Timestamp
	34, // 22: product.ProductShipping.created_at:type_name -> google.protobuf.Timestamp
	34, // 23: product.ProductShipping.updated_at:type_name -> google.protobuf.Timestamp
	34, // 24: product.ProductDiscount.expires_at:type_name -> google.protobuf.Timestamp
	34, // 25: product.ProductDiscount.created_at:type_name -> google.protobuf.Timestamp
	34, // 26: product.ProductDiscount.updated_at:type_name -> google.protobuf.Timestamp
	35, // 27: product.Product.discount_price:type_name -> google.protobuf.DoubleValue
	35, // 28: product.Product.weight:type_name -> google.protobuf.DoubleValue
	34, // 29: product.Product.created_at:type_name -> google.protobuf.Timestamp
	34, // 30: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	36, // 31: product.Product.brand_id:type_name -> google.protobuf.StringValue
	11, // 32: product.Product.brand:type_name -> product.Brand
	10, // 33: product.Product.images:type_name -> product.ProductImage
	12, // 34: product.Product.categories:type_name -> product.Category
	2,  // 35: product.Product.variants:type_name -> product.ProductVariant
	36, // 36: product.Product.default_variant_id:type_name -> google.protobuf.StringValue
	3,  // 37: product.Product.tags:type_name -> product.ProductTag
	4,  // 38: product.Product.attributes:type_name -> product.ProductAttribute
	5,  // 39: product.Product.specifications:type_name -> product.ProductSpecification
	6,  // 40: product.Product.seo:type_name -> product.ProductSEO
	7,  // 41: product.Product.shipping:type_name -> product.ProductShipping
	8,  // 42: product.Product.discount:type_name -> product.ProductDiscount
	34, // 43: product.ProductImage.created_at:type_name -> google.protobuf.Timestamp
	34, // 44: product.ProductImage.updated_at:type_name -> google.protobuf.Timestamp
	34, // 45: product.Brand.created_at:type_name -> google.protobuf.Timestamp
	34, // 46: product.Brand.updated_at:type_name -> google.protobuf.Timestamp
	34, // 47: product.Brand.deleted_at:type_name -> google.protobuf.Timestamp
	36, // 48: product.Category.parent_id:type_name -> google.protobuf.StringValue
	34, // 49: product.Category.created_at:type_name -> google.protobuf.Timestamp
	34, // 50: product.Category.updated_at:type_name -> google.protobuf.Timestamp
	34, // 51: product.Category.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 52: product.CreateProductRequest.product:type_name -> product.Product
	9,  // 53: product.UpdateProductRequest.product:type_name -> product.Product
	9,  // 54: product.ListProductsResponse.products:type_name -> product.Product
	11, // 55: product.ListBrandsResponse.brands:type_name -> product.Brand
	11, // 56: product.CreateBrandRequest.brand:type_name -> product.Brand
	12, // 57: product.ListCategoriesResponse.categories:type_name -> product.Category
	12, // 58: product.CreateCategoryRequest.category:type_name -> product.Category
	13, // 59: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	14, // 60: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	18, // 61: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	15, // 62: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	16, // 63: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	23, // 64: product.ProductService.CreateBrand:input_type -> product.CreateBrandRequest
	20, // 65: product.ProductService.GetBrand:input_type -> product.GetBrandRequest
	21, // 66: product.ProductService.ListBrands:input_type -> product.ListBrandsRequest
	27, // 67: product.ProductService.CreateCategory:input_type -> product.CreateCategoryRequest
	24, // 68: product.ProductService.GetCategory:input_type -> product.GetCategoryRequest
	25, // 69: product.ProductService.ListCategories:input_type -> product.ListCategoriesRequest
	28, // 70: product.ProductService.UploadImage:input_type -> product.UploadImageRequest
	30, // 71: product.ProductService.DeleteImage:input_type -> product.DeleteImageRequest
	32, // 72: product.ProductService.GenerateSKUPreview:input_type -> product.GenerateSKUPreviewRequest
	9,  // 73: product.ProductService.CreateProduct:output_type -> product.Product
	9,  // 74: product.ProductService.GetProduct:output_type -> product.Product
	19, // 75: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	9,  // 76: product.ProductService.UpdateProduct:output_type -> product.Product
	17, // 77: product.ProductService.DeleteProduct:output_type -> product.DeleteProductResponse
	11, // 78: product.ProductService.CreateBrand:output_type -> product.Brand
	11, // 79: product.ProductService.GetBrand:output_type -> product.Brand
	22, // 80: product.ProductService.ListBrands:output_type -> product.ListBrandsResponse
	12, // 81: product.ProductService.CreateCategory:output_type -> product.Category
	12, // 82: product.ProductService.GetCategory:output_type -> product.Category
	26, // 83: product.ProductService.ListCategories:output_type -> product.ListCategoriesResponse
	29, // 84: product.ProductService.UploadImage:output_type -> product.UploadImageResponse
	31, // 85: product.ProductService.DeleteImage:output_type -> product.DeleteImageResponse
	33, // 86: product.ProductService.GenerateSKUPreview:output_type -> product.GenerateSKUPreviewResponse
	73, // [73:87] is the sub-list for method output_type
	59, // [59:73] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	file_proto_product_proto_msgTypes[14].OneofWrappers = []any{
		(*GetProductRequest_Id)(nil),
		(*GetProductRequest_Slug)(nil),
	}
	file_proto_product_proto_msgTypes[20].OneofWrappers = []any{
		(*GetBrandRequest_Id)(nil),
		(*GetBrandRequest_Slug)(nil),
	}
	file_proto_product_proto_msgTypes[24].OneofWrappers = []any{
		(*GetCategoryRequest_Id)(nil),
		(*GetCategoryRequest_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
