server:
  port: "8080"
  environment: "development"
  jwtSecret: "${JWT_SECRET}"

services:
  product:
    host: "${PRODUCT_SERVICE_HOST:-localhost}"
    port: "${PRODUCT_SERVICE_PORT:-50051}"
  user:
    host: "localhost"
    port: "50052"
  order:
    host: "localhost"
    port: "50053"
  payment:
    host: "localhost"
    port: "50054"
  inventory:
    host: "localhost"
    port: "50055"
  cart:
    host: "localhost"
    port: "50056"
  search:
    host: "localhost"
    port: "50057"
  review:
    host: "localhost"
    port: "50058"
  notification:
    host: "localhost"
    port: "50059"
  shipping:
    host: "localhost"
    port: "50060"
  promotion:
    host: "localhost"
    port: "50061"
  recommendation:
    host: "localhost"
    port: "50062"



